routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('test', function(){
        \Maatwebsite\Excel\Facades\Excel::load('public/csv/1I.csv', function($reader){
            foreach($reader->get() as $alumno)
            {
            	if($alumno->nombre !== null && $alumno->nombre !== false)
            	{
            		dump($alumno->nombre);
	                \App\Alumno::create([
	                    'nombre' => $alumno->nombre,
	                    'grado' => $alumno->grado,
	                    'seccion' => $alumno->seccion,
	                    'cedula' => $alumno->cedula
	                ]);
            	}
            }
        });
});*/

Route::get('boletines', 'BoletinController@index')->name('boletin.index');

Route::post('boletin', 'BoletinController@show')->name('boletin.show');

Route::get('/', 'HomeController@index')->name('home');

Route::resource('admin', 'AdminController')->middleware(['auth', 'roles:director'])->except([
	'show'
]);

Route::resource('coordination', 'CoordinatorController')->middleware(['auth', 'roles:coordinador'])->except([
	'show'
]);

Route::group(['prefix' => 'materias', 'middleware' => ['auth', 'roles:tarea_materia']], function(){
	Route::get('/','MateriaController@index')->name('materias.index');
	Route::get('/create','MateriaController@create')->name('materias.create');
	//Route::get('/{id}','MateriaController@show')->name('materias.show');
	Route::post('/','MateriaController@store')->name('materias.store');
	Route::get('/{id}/edit','MateriaController@edit')->name('materias.edit');
	Route::put('/{id}','MateriaController@update')->name('materias.update');
	Route::delete('/{id}','MateriaController@destroy')->name('materias.destroy');
});
/*
Route::group(['prefix' => 'seccions', 'middleware' => ['auth', 'roles:tarea_seccion']], function(){
	Route::get('/','SeccionController@index')->name('seccions.index');
	Route::get('/create','SeccionController@create')->name('seccions.create');
	//Route::get('/{id}','SeccionController@show')->name('seccions.show');
	Route::post('/','SeccionController@store')->name('seccions.store');
	Route::get('/{id}/edit','SeccionController@edit')->name('seccions.edit');
	Route::put('/{id}','SeccionController@update')->name('seccions.update');
	Route::delete('/{id}','SeccionController@destroy')->name('seccions.destroy');
});
*/
Route::group(['prefix' => 'profesores', 'middleware' => ['auth', 'roles:tarea_profesor']], function(){
	Route::get('/','ProfesorController@index')->name('profesores.index');
	Route::get('/create','ProfesorController@create')->name('profesores.create');
	//Route::get('/{id}','ProfesorController@show')->name('profesores.show');
	Route::post('/','ProfesorController@store')->name('profesores.store');
	Route::get('/{id}/edit','ProfesorController@edit')->name('profesores.edit');
	Route::put('/{id}','ProfesorController@update')->name('profesores.update');
	Route::delete('/{id}','ProfesorController@destroy')->name('profesores.destroy');
});

Route::group(['prefix' => 'notas', 'middleware' => ['auth', 'roles:tarea_notas']], function(){
	Route::get('/','NotaController@index')->name('notas.index');
	Route::get('/create','NotaController@create')->name('notas.create');
	Route::post('/show','NotaController@show')->name('notas.crear');
	Route::post('/','NotaController@store')->name('notas.store');
	Route::delete('/{id}', 'NotaController@destroy')->name('notas.destroy');
	Route::get('/alumnos_json', 'NotaController@alumnosJson')->name('notas.alumnos');
});

Route::group(['prefix' => 'alumnos', 'middleware' => ['auth', 'roles:tarea_alumno']], function(){
	Route::get('/','AlumnoController@index')->name('alumnos.index');
	Route::get('/create','AlumnoController@create')->name('alumnos.create');
	//Route::get('/{id}','AlumnoController@show')->name('alumnos.show');
	Route::post('/','AlumnoController@store')->name('alumnos.store');
	Route::get('/{id}/edit','AlumnoController@edit')->name('alumnos.edit');
	Route::put('/{id}','AlumnoController@update')->name('alumnos.update');
	Route::delete('/{id}','AlumnoController@destroy')->name('alumnos.destroy');
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

resources/views/admin/create.blade.php
@extends('layouts.default')

@section('title', 'Crear')

@section('content')
<h2 class="text-title">Creación</h2>
<div class="content-show">
  <form action="{{ route('admin.store') }}" method="post">
    @csrf
    @include('admin.form')
    <button class="btn btn-create">
      Crear
    </button>
    <a href="{{ route('admin.index') }}" class="btn btn-create">Volver</a>
  </form>
</div>
@endsection

resources/views/admin/edit.blade.php
@extends('layouts.default')

@section('title', 'Editar - '. $user->name)

@section('content')
<h2 class="text-title">Editar</h2>
<div class="content-show">
  <form action="{{ route('admin.update', $user->id) }}" method="post">
    @csrf
    @method('PUT')
    @include('admin.form')
    <button class="btn btn-create">
      Editar
    </button>
    <a href="{{ route('admin.index') }}" class="btn btn-create">Volver</a>
  </form>
</div>
@endsection

resources/views/admin/form.blade.php
    <div class="form-group row">
      <label for="inputPassword" class="col-sm-2 col-form-label">Nombre</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" name="name" id="inputtext" value="{{ $user->name ?? old('name') }}">
      </div>
    </div>
    <div class="form-group row">
      <label for="inputtext" class="col-sm-2 col-form-label">Correo Electrónico</label>
      <div class="col-sm-10">
        <input type="email" class="form-control" name="email" id="inputPassword" value="{{ $user->email ?? old('email') }}">
      </div>

    </div>
    <div class="form-group row">
      <label for="inputPassword" class="col-sm-2 col-form-label">Contraseña</label>
      <div class="col-sm-10">
        <input type="password" class="form-control" name="password" id="inputPassword">
      </div>
    </div>
    <div class="form-group row">
      <label for="inputPassword" class="col-sm-2 col-form-label">Confirmar Contraseña</label>
      <div class="col-sm-10">
        <input type="password" class="form-control" name="password_confirmation" id="inputPassword">
      </div>
    </div>
    <div class="form-group row">
      <label for="inputPassword" class="col-sm-2 col-form-label">Niveles</label>
      <div class="col-sm-10">
        {{ Form::select('role', $roles, null, ['class' => 'form-control']) }}
      </div>
    </div>

resources/views/admin/index.blade.php
@extends('layouts.default')

@section('title', 'Administración - Panel Principal')

@section('content')
<div class="container-fluid">
  @if(Session::has('flash'))
    <h5 class="info-msg">{{Session::get('flash')}}</h5>
  @endif

<div class="col-12 content-title-search">
  <h1 class="col-8 left">
    <i class="fa faw fa-landmark"></i> funcionarios disponibles
  </h1>
  <span class="col-4 right">
    <a href="{{ route('admin.create') }}" class="btn btn-create"><i class="fas fa-lg fa-plus"></i></a>
    <span class="form-group">
      <form action="{{ route('admin.index') }}" method="get">
        <input type="text" name="admin" placeholder="Buscar..." class="search-input">
        <button class="btn btn-create">Enviar</button>
      </form>
    </span>
  </span>
</div>

<table class="table table-content">
  <thead class="table-header">
    <th>
      nombre
    </th>
    <th>
      correo electrónico
    </th>
    <th>
      Niveles
    </th>
    <th>
      ultima vez actualizado
    </th>
    <th>
      acciones
    </th>
  </thead>
  <tbody class="table-body">
    @foreach($admins as $user)
    <tr>
      <td>
        {{ $user->name }}
      </td>
      <td>
        {{ $user->email }}
      </td>
      <td class="table-roles">
        {{ $user->roles->pluck('nombre_descriptivo')->implode(', ') }}
      </td>
      <td>
        {{ $user->updated_at }}
      </td>
      <td>
        <div class="btn-group-sm">
          <a href="{{ route('admin.edit', $user->id) }}" class="btn btn-create"><i class="fas fa-sm fa-edit"></i></a>
          <form method="post" action="{{ route('admin.destroy', $user->id) }}">
            @method('DELETE')
            @csrf
            <button class="btn-sm btn-create"><i class="fas fa-sm fa-trash"></i></button>
          </form>
        </div>
      </td>
    </tr>
    @endforeach
  </tbody>
</table>  
  <div class="row justify-content-center">
    {{ $admins->appends(request()->query())->links('paginate.default') }} 
  </div>
</div>
@endsection

resources/views/admin/show.blade.php
@extends('layouts.default')

@section('content')
<div class="container">
      <div class="card card-login mx-auto mt-5 login-body">
        <div class="card-header login-header">{{ $user->name }}</div>
        <div class="card-body">
          
        </div>
      </div>
    </div>
@endsection